[font]
size = 10.0

[font.bold]
family = "Atkynson Mono Nerd Font" 
style = "Bold"

[font.bold_italic]
family = "Atkynson Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Atkynson Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Atkynson Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.8
