[font]
size = 14.0

[font.bold]
family = "Roboto Mono Nerd Font" 
style = "Bold"

[font.bold_italic]
family = "Roboto Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Roboto Mono Nerd Font"
style = "Regular"

[window]
startup_mode = "Maximized"
opacity = 0.8
